export const ActionTypes = {
    FETCH_GAME: "FETCH_GAME",
    SELECTED_GAME: "SELECTED_GAME",
    REMOVE_SELECTED_GAME: "REMOVE_SELECTED_GAME",
    NEXT_PAGE: "NEXT_PAGE",
    PREV_PAGE: "PREV_PAGE",
    IS_LOADING: "IS_LOADING",
    RESET_PAGE: "RESET_PAGE",
    SEARCH_GAME: "SEARCH_GAME",
    SEARCH_ID: "SEARCH_ID",
}